### ISSUE TITLE
Recommend switching from CMD to ENTRYPOINT

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/cmd-forwarder-ovs#4]
I recommend switching from CMD to ENTRYPOINT [here](https://github.com/networkservicemesh/cmd-forwarder-ovs/blob/93801dc0f7ccc6a532eea81b4f228093e05e008c/Dockerfile#L23)

CMD runs a shell which then runs what is specified.

ENTRYPOINT simply runs what is specified

When K8s tries to delete a Pod, PAUSE sends SIGTERM to the 
running process in the container.  After 30s, if the process
has not exited, PAUSE sends SIGKILL.

The container isn't *actually* deleted until PAUSE exits.
PAUSE will exit when all its children are dead.

Using CMD puts a shell between the PAUSE container and the
running process.  The shell doesn't properly pass on the SIGTERM.

Using ENTRYPOINT removes that intermediate shell, and allows
the container to exit much much faster in K8s.

**Comment by pperiyasamy** [comment]
This is addressed in docker files [1](https://github.com/networkservicemesh/cmd-forwarder-ovs/blob/main/Dockerfile#L39) and [2](https://github.com/networkservicemesh/cmd-forwarder-ovs/blob/main/Dockerfile.use-host-ovs#L27). closing the issue.
