### ISSUE TITLE
ovs forwarder not getting started 

### ISSUE THREAD

**Issue by pperiyasamy** [networkservicemesh/cmd-forwarder-ovs#74]
the ovs forwarder doesn't start with latest deployments-k8s [example](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/ovs) and it seems to be just hanging on `phase 5: register forwarder with the registry ` step. 

Logs attached.

**Comment by pperiyasamy** [comment]
[ovs-forwarder-bringup-issue.log](https://github.com/networkservicemesh/cmd-forwarder-ovs/files/7705782/ovs-forwarder-bringup-issue.log)

**Comment by pperiyasamy** [comment]
This looks like just a connectivity issue in control plane on the k8s primary networking because  nsm mgr pod is not able to reach remote registry pod, but when both nsm mgr and registry pods are co located, then things are working. 
I will debug what went wrong on the control plane network.

**Comment by pperiyasamy** [comment]
@edwarnicke This issue occurred due to misconfig of egress interface used for calico primary network, after correcting it the forwarder comes up properly now. closing the issue.

**Comment by edwarnicke** [comment]
@pperiyasamy Excellent news!
